apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: owlvey-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /site
        pathType: Prefix
        backend:
          serviceName: owlvey-site
          servicePort: 80