apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: owlvey
spec:
  # ClusterIP NodePort
  type: LoadBalancer  
  selector:
    app: owlvey-api
  ports:
    - name: http
      protocol: TCP      
      port: 47000
      targetPort: 80 
      # nodePort: 30036